### ISSUE TITLE
Make Staking Stable

### ISSUE THREAD

**Issue by 0x4007** [0x4007/uad.ubq.fi#1]
The current uad.ubq.fi interface is hosted off of my development branch as a stopgap until we redeploy. 

This is essential infrastructure to keep alive for our stakers/farmers. 

Staking view does not always render. I presume its RPC related. 

Make sure its stable. 

This will be a manual payout.

**Comment by 0x4007** [comment]
I'm a bit lazy to reconfig my config because I'm using an updated system on my "org"

So I'll just max out the priority to get the pricing in the ballpark of our normal budgets

**Comment by Keyrxng** [comment]
It's odd seeing a react codebase in amongst the rest of the UIs

The provider being used is a fallback provider that often fails to reach quorum and throws an error in one of the wrappers that's stopping rendering, now it's either connectkit or wagmi but I wasn't able to find who the culprit is on first pass

I'll work on this tomorrow

**Comment by 0x4007** [comment]
> It's odd seeing a react codebase in amongst the rest of the UIs

This is the oldest UI. I decided that we should proceed with React because its the most common framework so I figured it would be the most maintainable. Boy, was I wrong!

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0x0c38c3ad1adbb2f53855bdb94b15393f64e23e8eff0f8e176cd42187124a8a9f
